SELECT M.MODIFY_NO,
        M.DEMAND_DT,
        M.DEMAND_CD,
        E1.EMP_NM AS DEMAND_NM,
        DP.DEPT_NM2 AS DEMAND_COM_NM,
        M.DEMAND_BEGIN_CD,
        M.DEMAND_MGM_CD,  
        M7.MGM_NM AS DEMAND_MGM_NM,
        M.PROD_FG,
        M1.MGM_NM AS PROD_FG_NM,
        M.DEVMGM_FG,
        M6.MGM_NM AS DEVMGM_FG_NM,
        F.MOD_CD,
        CASE WHEN M.PROD_FG = 'G1' THEN M10.MGM_NM ELSE M2.MGM_NM END AS MOD_NM,
        M.FILE_CD,
        F.FILE_NM,
        M.FILE_DC,
        CASE WHEN M.FILE_CD = '예외' AND ISNULL(M.FILE_DC,'')<>'' THEN M.FILE_DC ELSE F.FILE_NM END FILE_NM_DC,
        M.PROJECT_FG,
        M.PROJECT_CD,
        PT.PROJECT_NM,
        M.CUST_ID,
        T.CUST_NM,            
        M.FILE_DT,            
        M.WORK_MGM_CD,
        M8.MGM_NM AS WORK_MGM_NM,
        M.HAND_MGM_CD,
        M9.MGM_NM AS HAND_MGM_NM,
        M.CONFIRM_DT,
        M.CONFIRM_CD,
        E3.EMP_NM AS CONFIRM_NM,
        M.CONFIRM_TO_EMP_CD,
        E4.EMP_NM AS ONFIRM_TO_EMP_NM,
        M.PLAN_CD,
        E5.EMP_NM AS PLAN_NM,
        M.FIX_CD,
        E2.EMP_NM AS FIX_NM,
        M.GUESS_DT,
        D.DEVEL_CD,
        D.EDPLAN_DT,
        D.TEST_DC,
        M.DEMAND_DC,
        W.STATE_1_NM AS WEBCALL_STATE_1_NM,
        CASE WHEN ISNULL(D.TEST_FG,'01') <> '01' THEN '최종-'+M5.MGM_NM
            WHEN ISNULL(D.TEST2_FG,'01') <> '01' THEN '2차-'+M4.MGM_NM
            WHEN ISNULL(D.TEST1_FG,'01') <> '01' THEN '1차-'+M3.MGM_NM
            ELSE NULL END TEST_STATUS,
        CASE WHEN M.HAND_DC IS NULL OR DATALENGTH(M.HAND_DC) = 0 THEN ''
            ELSE M.HAND_DC END HAND_DC,           
        CASE WHEN M.ADD_DC IS NULL OR DATALENGTH(M.ADD_DC) = 0 THEN ''
            ELSE M.ADD_DC END ADD_DC,   
        TE.TEST_EMP_CD
    FROM DMODIFY AS M
        LEFT OUTER JOIN DEVMGM_D F ON F.PROD_FG = M.PROD_FG AND F.DEVMGM_FG = M.DEVMGM_FG AND F.FILE_CD = M.FILE_CD
        LEFT OUTER JOIN SEMP E1 ON E1.EMP_CD = M.DEMAND_CD
        LEFT OUTER JOIN SEMP E2 ON E2.EMP_CD = M.FIX_CD
        LEFT OUTER JOIN SEMP E3 ON E3.EMP_CD = M.CONFIRM_CD
        LEFT OUTER JOIN SEMP E4 ON E4.EMP_CD = M.CONFIRM_TO_EMP_CD
        LEFT OUTER JOIN SEMP E5 ON E5.EMP_CD = M.PLAN_CD
        LEFT OUTER JOIN SDEPT DP ON DP.DEPT_FG = E1.DEPT_FG AND DP.DEPT_CD = E1.DEPT_CD
        LEFT OUTER JOIN DEVEL D ON D.MODIFY_NO = M.MODIFY_NO AND D.CLONE_FG IN ('00', '01')
        LEFT OUTER JOIN DCTRL_MGM_D M1 ON M1.CTRL_CD = 'GT' AND M1.MGM_CD = M.PROD_FG
        LEFT OUTER JOIN DCTRL_MGM_D M2 ON M2.CTRL_CD = 'MD' AND M2.MGM_CD = F.MOD_CD
        LEFT OUTER JOIN DCTRL_MGM_D M3 ON M3.CTRL_CD = 'TG' AND M3.MGM_CD = D.TEST1_FG
        LEFT OUTER JOIN DCTRL_MGM_D M4 ON M4.CTRL_CD = 'TG' AND M4.MGM_CD = D.TEST2_FG
        LEFT OUTER JOIN DCTRL_MGM_D M5 ON M5.CTRL_CD = 'TG' AND M5.MGM_CD = D.TEST_FG
        LEFT OUTER JOIN DCTRL_MGM_D M6 ON M6.CTRL_CD = 'DF' AND M6.MGM_CD = F.DEVMGM_FG
        LEFT OUTER JOIN DCTRL_MGM_D M7 ON M7.CTRL_CD = 'MT' AND M7.MGM_CD = M.DEMAND_MGM_CD
        LEFT OUTER JOIN DCTRL_MGM_D M8 ON M8.CTRL_CD = 'UT' AND M8.MGM_CD = M.WORK_MGM_CD
        LEFT OUTER JOIN DCTRL_MGM_D M9 ON M9.CTRL_CD = 'CT' AND M9.MGM_CD = M.HAND_MGM_CD
        LEFT OUTER JOIN DCTRL_MGM_D M10 ON M10.CTRL_CD = 'GM' AND M10.MGM_CD = F.MOD_CD
        LEFT OUTER JOIN SPROJECT PT ON PT.PROJECT_FG = M.PROJECT_FG AND PT.PROJECT_CD = M.PROJECT_CD
        LEFT OUTER JOIN STRADE T ON T.ROW_ID = M.CUST_ID
        LEFT OUTER JOIN WEBCALL_SYNC_STATE W ON W.SEQ_DEV = M.SEQ_DEV
        LEFT OUTER JOIN ( 
            SELECT T.DEVEL_NO,
                    STUFF(
                        (
                            SELECT DISTINCT '|' + A.TEST_EMP_CD
                                FROM DTEST_HISTORY AS A
                                WHERE A.DEVEL_NO = T.DEVEL_NO FOR XML PATH ('')
                        )
                    , 1, 1, '') AS TEST_EMP_CD
                FROM DTEST_HISTORY AS T
                GROUP BY T.DEVEL_NO ) TE ON D.DEVEL_NO = TE.DEVEL_NO                                      
    WHERE (
        M.PROD_FG IN('Q1','AX','DT', 'Q2', 'Q3', 'Q4') 
        OR CASE WHEN M.PROD_FG = 'G1' AND F.MOD_CD IN('B2', 'T2', 'TX', 'TH') THEN 1 ELSE 0 END = 1
    )
        AND ISNULL(M.CONFIRM_CD, '') <> ''
        AND M.DEMAND_DT >= '20180101'
        AND ( 
            CONVERT(NVARCHAR, M.MODIFY_DT, 112) = @date OR 
            CONVERT(NVARCHAR, M.INSERT_DT, 112) = @date OR 
            CONVERT(NVARCHAR, D.MODIFY_DT, 112) = @date
        )