SELECT ES.EST_NO,
        ES.EST_FG,
        CASE WHEN ES.PROCESS_FG IN ('60','70','80','90') THEN '50' ELSE ES.PROCESS_FG END PROCESS_FG,
        CONVERT(NVARCHAR, ES.REQ_DT, 112) REQ_DT,
        CONVERT(NVARCHAR, ES.WRT_DT, 112) WRT_DT,
        ES.DEPT_CD,
        ES.EMP_CD,
        ES.TEL_DC,
        ES.CUST_NM,
        ES.CUST_FG,
        ES.CUST_ADDR_DC,
        ES.CUST_EMP_DC,
        ES.CUST_TEL_DC,
        ES.PROD_FG,
        ES.DEVMGM_FG,
        ES.MOD_CD,
        ES.FILE_CD,
        ES.REQUEST_DC,
        ES.PROCESS_DC,
        ES.ESTIMATION_DC,
        ES.PROCESS_EMP_CD,
        ES.RECEIVE_DT,
        ES.CONFIRM_DT,
        ES.COMPLETE_DT,
        ES.ISSUE_DC,
        '' CANCEL_DC,
        M1.MGM_NM        CUST_FG_NM,
        M2.MGM_NM        PROD_FG_NM,
        M3.MGM_NM        MOD_NM,
        M4.MGM_NM        EST_FG_NM,
        M6.MGM_NM        DEVMGM_FG_NM,
        M7.MGM_NM        PROCESS_FG_NM,
        FI.FILE_NM,
        E1.EMP_NM,
        E2.EMP_NM        PROCESS_EMP_NM,
        E2.TEL_NO        PROCESS_EMP_TEL_NO,
        D1.DEPT_NM,
        ES.REQUEST_FILE_NB,
        ES.PROCESS_FILE_NB,
        ISNULL(A3.FILE_CT,0) REQUEST_FILE_CT,
        ISNULL(A1.FILE_CT,0) PROCESS_FILE_CT,
        '' REQUEST_FILE_XML,
        '' PROCESS_FILE_XML,
        DB.BUSINESS_CT,
        ES.SATISFACTION,
        AM.SUM_ITEM_AM,
        ES.DEVEL_TYPE,                        
        ES.INTERCONNECTION_SYSTEM 
    FROM DESTIMATION ES
        LEFT OUTER JOIN DCTRL_MGM_D  M1 ON M1.CTRL_CD = 'PH' AND M1.MGM_CD = ES.CUST_FG
        LEFT OUTER JOIN DCTRL_MGM_D  M2 ON M2.CTRL_CD = 'GT' AND M2.MGM_CD = ES.PROD_FG
        LEFT OUTER JOIN DCTRL_MGM_D  M3 ON M3.CTRL_CD = 'MD' AND M3.MGM_CD = ES.MOD_CD
        LEFT OUTER JOIN DCTRL_MGM_D  M4 ON M4.CTRL_CD = 'E1' AND M4.MGM_CD = ES.EST_FG         
        LEFT OUTER JOIN DCTRL_MGM_D  M6 ON M6.CTRL_CD = 'DF' AND M6.MGM_CD = ES.DEVMGM_FG
        LEFT OUTER JOIN DCTRL_MGM_D  M7 ON M7.CTRL_CD = 'E2' AND M7.MGM_CD = CASE WHEN ES.PROCESS_FG IN ('60','70','80','90') THEN '50' ELSE ES.PROCESS_FG END                        
        LEFT OUTER JOIN DEVMGM_D     FI ON FI.PROD_FG = ES.PROD_FG AND FI.DEVMGM_FG = ES.DEVMGM_FG AND FI.FILE_CD = ES.FILE_CD
        LEFT OUTER JOIN SEMP         E1 ON E1.EMP_CD = ES.EMP_CD
        LEFT OUTER JOIN SEMP         E2 ON E2.EMP_CD = ES.PROCESS_EMP_CD
        LEFT OUTER JOIN SDEPT        D1 ON D1.DEPT_CD = ES.DEPT_CD
        LEFT OUTER JOIN SATTACH_FILE A1 ON A1.FILE_FG = 'P' AND A1.FILE_NB = ES.PROCESS_FILE_NB
        LEFT OUTER JOIN SATTACH_FILE A3 ON A3.FILE_FG = 'B' AND A3.FILE_NB = ES.REQUEST_FILE_NB
        LEFT OUTER JOIN (
            SELECT EST_NO, COUNT(1) BUSINESS_CT
                FROM DBUSINESS
                GROUP BY EST_NO
        ) DB ON DB.EST_NO = ES.EST_NO
        LEFT OUTER JOIN (  
            SELECT EST_NO, SUM(ITEM_AM) SUM_ITEM_AM                                   
                FROM DESTIMATION_D2
                GROUP BY EST_NO
        ) AM ON AM.EST_NO = ES.EST_NO
    WHERE ES.PROD_FG IN('Q1','AX','DT', 'Q2', 'Q3', 'Q4') 
        AND ES.PROCESS_FG <> '10'
        AND ES.REQ_DT >= '20180101'
        AND ( CONVERT(NVARCHAR, ES.MODIFY_DT, 112) = @date OR CONVERT(NVARCHAR, ES.INSERT_DT, 112) = @date )