SELECT PT.PROJECT_CD,
		PT.PROJECT_FG,
		PT.PROJECT_NM,
		M1.MGM_NM        PROD_FG_NM,
		PT.MOD_CD,
		CASE WHEN PT.PROD_FG = 'G1' THEN M3.MGM_NM ELSE M2.MGM_NM END MOD_NM,
		CASE WHEN PT.PROD_FG = 'BC' THEN 'BizCube10'
		WHEN PT.PROD_FG = 'G1' AND PT.PROJECT_FG = 'P1' THEN '프로젝트(D-ERP)'
		WHEN PT.PROD_FG <> 'G1' AND PT.PROJECT_FG = 'P1' THEN '프로젝트(iCUBE)'
		WHEN PT.PROD_FG = 'G1' AND PT.PROJECT_FG = 'P9' THEN '전용개발(D-ERP)'
		WHEN PT.PROD_FG <> 'G1' AND PT.PROJECT_FG = 'P9' THEN '전용개발(iCUBE)'
		WHEN PT.PROD_FG = 'G1' AND PT.PROJECT_FG = 'P8' THEN '패키지유지보수(D-ERP)'
		WHEN PT.PROD_FG <> 'G1' AND PT.PROJECT_FG = 'P8' THEN '패키지유지보수(iCUBE)'
		WHEN PT.PROD_FG = 'G1' AND PT.PROJECT_FG = 'PA' THEN '전용개발유지보수(D-ERP)'
		WHEN PT.PROD_FG <> 'G1' AND PT.PROJECT_FG = 'PA' THEN '전용개발유지보수(iCUBE)'
		ELSE null END PROJECT_KIND_NM,
		CASE WHEN PT.PROJECT_FG IN('PA', 'P9') THEN '전용개발' ELSE '패키지' END DEVMGM_FG_NM,
		CASE WHEN PT.PROJECT_FG IN('P1', 'P9') THEN '프로젝트' ELSE '유지보수' END PROJECT_FG_NM,
		PT.START_DT,
		PT.EMP_CD,
		PT.SO_DT,
		PT.SCHED_DT, 
		PT.DEVEL_TYPE,
		PT.INTERCONNECTION_SYSTEM,
		CASE WHEN PT.DIFFICULTY_LV = '1' THEN '상'
		WHEN PT.DIFFICULTY_LV = '2' THEN '중'
		WHEN PT.DIFFICULTY_LV = '3' THEN '하'
		ELSE null END DIFFICULTY_LV,
		DA.IN_FARE_AM,
		ST.CUST_NM       PROJECT_CUST_NM,
		PT.REMARK_DC
    FROM SPROJECT PT
		LEFT OUTER JOIN DCTRL_MGM_D M1 ON M1.CTRL_CD = 'GT' AND M1.MGM_CD = PT.PROD_FG
		LEFT OUTER JOIN DCTRL_MGM_D M2 ON M2.CTRL_CD = 'MD' AND M2.MGM_CD = PT.MOD_CD
		LEFT OUTER JOIN DCTRL_MGM_D M3 ON M3.CTRL_CD = 'GM' AND M3.MGM_CD = PT.MOD_CD
		LEFT OUTER JOIN DPROJECT_AM DA ON DA.PROJECT_CD = PT.PROJECT_CD
		LEFT OUTER JOIN STRADE      ST ON ST.ROW_ID = PT.CUST_CD
    WHERE (
		PT.PROD_FG IN('Q1','AX','DT', 'Q2', 'Q3', 'Q4', 'G1', 'BC') 
		OR CASE WHEN PT.PROD_FG = 'G1' AND PT.MOD_CD IN('B2', 'T2', 'TX', 'TH') THEN 1 ELSE 0 END = 1
	)
		AND ISNULL(PT.PROJECT_CD, '') <> ''
		AND ISNULL(PT.EMP_CD, '') <> ''	                   
		AND ISNULL(PT.PROJECT_CD, '') LIKE 'P2-%'
		AND ( CONVERT(NVARCHAR, PT.MODIFY_DT, 112) = @date OR CONVERT(NVARCHAR, PT.INSERT_DT, 112) = @date OR CONVERT(NVARCHAR, DA.MODIFY_DT, 112) = @date OR CONVERT(NVARCHAR, DA.INSERT_DT, 112) = @date )